
services:
  app:
    container_name: app
    build:
      context: ./
      target: development
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      BOT_USERNAME: ${BOT_USERNAME}
      API_PORT: ${API_PORT}
      TG_TOKEN: ${TG_TOKEN}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./alembic/versions:/app/alembic/versions
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: data_inspector_db
    restart: always
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: null
