"""questions and alias

Revision ID: 1bb47e061820
Revises: 1a97329c62fb
Create Date: 2025-09-09 20:09:33.385919

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1bb47e061820"
down_revision = "1a97329c62fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("answer", sa.TEXT(), nullable=True),
        sa.Column("interview_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.add_column("interviews", sa.Column("alias_id", sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interviews", "alias_id")
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
