"""chats

Revision ID: 25f7bd94b45f
Revises: 1bb47e061820
Create Date: 2025-09-09 22:00:59.245359

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "25f7bd94b45f"
down_revision = "1bb47e061820"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_id"), "chats", ["id"], unique=False)
    op.add_column("candidates", sa.Column("chat_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "candidates", "chats", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "candidates", type_="foreignkey")
    op.drop_column("candidates", "chat_id")
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
