"""alias

Revision ID: e4c171ce624c
Revises: 5937d025cb9f
Create Date: 2025-09-09 19:14:29.253192

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e4c171ce624c"
down_revision = "5937d025cb9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interviews", sa.Column("alias_id", sa.String(length=12), nullable=True)
    )
    op.create_unique_constraint("unique_alias_id", "interviews", ["alias_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "interviews", type_="unique")
    op.drop_column("interviews", "alias_id")
    # ### end Alembic commands ###
