"""unused fields

Revision ID: 1a97329c62fb
Revises: d3ac1c9c6710
Create Date: 2025-09-09 18:13:13.318851

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1a97329c62fb"
down_revision = "d3ac1c9c6710"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidates", "first_name")
    op.drop_column("candidates", "last_name")
    op.drop_column("candidates", "patronymic")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidates",
        sa.Column("patronymic", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "candidates",
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "candidates",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
